package Mobile_language.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import java.awt.GridLayout;
import javax.swing.SwingUtilities;

public class MobileDesigner extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    public void insertUpdate(DocumentEvent p0) {
      update();
    }
    public void removeUpdate(DocumentEvent p0) {
      update();
    }
    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };

  /*package*/ ActionListener actionlist = new ActionListener() {
    public void actionPerformed(ActionEvent p0) {
      update();
    }
  };

  /*package*/ String[] s = {"a", "b"};
  private int displayValue = 0;
  /*package*/ int osValue = 0;
  /*package*/ int totalCost = 0;


  private JLabel f = new JLabel("");
  private JLabel feature = new JLabel("Choose Mobile Features");




  public MobileDesigner() {
    setTitle("MobileDesigner");
    setLayout(new GridLayout(0, 2));
    add(feature);
    add(f);




    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }
  public void update() {

    try {
    } catch (NumberFormatException e) {
    }
    int ostype;
    OS_a.addActionListener(actionlist);
    ostype = OS_a.getSelectedIndex();
    switch (ostype) {
      case 0:
        osValue = 40;
        break;
      case 1:
        osValue = 61;
        break;
      case 2:
        osValue = 55;
        break;
      case 3:
        osValue = 50;
        break;
    }
    System.out.print(ostype);

    int displayType;

    Display_a.addActionListener(actionlist);
    displayType = Display_a.getSelectedIndex();
    switch (displayType) {
      case 0:
        displayValue = 10;
        break;
      case 1:
        displayValue = 20;
        break;
      case 2:
        displayValue = 30;
        break;
      case 3:
        displayValue = 40;
        break;
      case 4:
        displayValue = 50;
        break;
      case 5:
        displayValue = 60;
        break;
    }
    System.out.print(displayValue);
    int finalCost = osValue + displayValue;
    outputField_a.setText(Integer.toString(finalCost));
  }


  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new MobileDesigner();
      }
    });
  }
}
