package main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import java.util.Collection;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.query.ReferenceTargetQuery;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetPropertyValue_6924493648261277925(final PropertyMacroContext _context) {
    return _context.createUniqueName("OS", null);
  }
  public static Object propertyMacro_GetPropertyValue_2385122351189271429(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x6018be491a138f3aL, 0x6018be491a138f71L, "Type"));
  }
  public static Object propertyMacro_GetPropertyValue_8581169171143915973(final PropertyMacroContext _context) {
    return _context.createUniqueName("Display", null);
  }
  public static Object propertyMacro_GetPropertyValue_8581169171143966575(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x77166fe56b8cf336L, 0x77166fe56b8cf354L, "Type"));
  }
  public static Object propertyMacro_GetPropertyValue_4160282296009002492(final PropertyMacroContext _context) {
    return _context.createUniqueName("inputFeature", null);
  }
  public static Object propertyMacro_GetPropertyValue_4160282296009027177(final PropertyMacroContext _context) {
    return _context.createUniqueName("outputField", null);
  }
  public static Object propertyMacro_GetPropertyValue_4160282296008949951(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_4160282296009146140(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_4160282296009314972(final PropertyMacroContext _context) {
    return _context.createUniqueName("i", null);
  }
  public static Object propertyMacro_GetPropertyValue_4160282296008733983(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_6924493648262274376(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x6018be491a138f3aL, 0x6018be491a138f71L, "Type"));
  }
  public static Object referenceMacro_GetReferent_4160282296009532596(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f215d2L, 0x39bc4ab4c2f215eeL, "Feature")), "LocalVar");
  }
  public static Object referenceMacro_GetReferent_6924493648261366371(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "OSDeclaration");
  }
  public static Object referenceMacro_GetReferent_6924493648261404983(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "OSDeclaration");
  }
  public static Object referenceMacro_GetReferent_8581169171144192298(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "DisplayDeclaration");
  }
  public static Object referenceMacro_GetReferent_8581169171144274280(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "DisplayDeclaration");
  }
  public static Object referenceMacro_GetReferent_4160282296009158684(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "InputFeatureDeclaration");
  }
  public static Object referenceMacro_GetReferent_4160282296009177263(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "InputFeatureDeclaration");
  }
  public static Object referenceMacro_GetReferent_4160282296009276059(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "OutputFieldDeclaration");
  }
  public static Object referenceMacro_GetReferent_4160282296009396079(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LocalVar");
  }
  public static Object referenceMacro_GetReferent_4160282296009417459(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "InputFeatureDeclaration");
  }
  public static Iterable<SNode> sourceNodesQuery_6924493648261277918(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x6018be491a0c482aL, "OS"));
  }
  public static Iterable<SNode> sourceNodesQuery_2385122351189019082(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collectMany(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x6018be491a0c482aL, "OS")), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x6018be491a06ec5fL, 0x6018be491a13d30fL, "OSType"));
  }
  public static Iterable<SNode> sourceNodesQuery_8581169171143854468(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x77166fe56b90b512L, "Display"));
  }
  public static Iterable<SNode> sourceNodesQuery_8581169171143966582(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.collectMany(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x77166fe56b90b512L, "Display")), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x77166fe56b8cebf6L, 0x77166fe56b8cf21fL, "DisplayType"));
  }
  public static Iterable<SNode> sourceNodesQuery_4160282296008993611(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x39bc4ab4c2f1ce4eL, "InputFeature"));
  }
  public static Iterable<SNode> sourceNodesQuery_4160282296009027170(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x39bc4ab4c2f1eff3L, "OutputField"));
  }
  public static Iterable<SNode> sourceNodesQuery_6924493648261315010(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x6018be491a0c482aL, "OS"));
  }
  public static Iterable<SNode> sourceNodesQuery_8581169171144201916(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x77166fe56b90b512L, "Display"));
  }
  public static Iterable<SNode> sourceNodesQuery_4160282296009134437(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x39bc4ab4c2f1ce4eL, "InputFeature"));
  }
  public static Iterable<SNode> sourceNodesQuery_4160282296009263824(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x39bc4ab4c2f1eff3L, "OutputField"));
  }
  public static Iterable<SNode> sourceNodesQuery_4160282296009307487(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x39bc4ab4c2f1ce4eL, "InputFeature"));
  }
  public static Iterable<SNode> sourceNodesQuery_4160282296009383858(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L, 0x39bc4ab4c2f1ce4eL, "InputFeature"));
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("6924493648261277918", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("2385122351189019082", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("8581169171143854468", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("8581169171143966582", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4160282296008993611", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4160282296009027170", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("6924493648261315010", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("8581169171144201916", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4160282296009134437", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4160282296009263824", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4160282296009307487", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4160282296009383858", new QueriesGenerated.SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6924493648261277918(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2385122351189019082(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8581169171143854468(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8581169171143966582(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4160282296008993611(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4160282296009027170(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_6924493648261315010(ctx));
        case 7:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8581169171144201916(ctx));
        case 8:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4160282296009134437(ctx));
        case 9:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4160282296009263824(ctx));
        case 10:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4160282296009307487(ctx));
        case 11:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4160282296009383858(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("6924493648261277924", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "os"));
    pvqMethods.put("2385122351189271428", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "OSTypes"));
    pvqMethods.put("8581169171143915972", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Display"));
    pvqMethods.put("8581169171143966574", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "DisplayType"));
    pvqMethods.put("4160282296009002491", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "inputFeature"));
    pvqMethods.put("4160282296009027176", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "outputField"));
    pvqMethods.put("4160282296008949950", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Mobile"));
    pvqMethods.put("4160282296009146139", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "Title"));
    pvqMethods.put("4160282296009314971", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "i"));
    pvqMethods.put("4160282296008733982", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "MobileImpl"));
    pvqMethods.put("6924493648262274375", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "s"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetPropertyValue_6924493648261277925(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetPropertyValue_2385122351189271429(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8581169171143915973(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8581169171143966575(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4160282296009002492(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4160282296009027177(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4160282296008949951(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4160282296009146140(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4160282296009314972(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4160282296008733983(ctx);
        case 10:
          return QueriesGenerated.propertyMacro_GetPropertyValue_6924493648262274376(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, ReferenceTargetQuery> rtqMethods = new HashMap<String, ReferenceTargetQuery>();
  {
    rtqMethods.put("4160282296009532595", new QueriesGenerated.RTQ(0, "i"));
    rtqMethods.put("6924493648261366370", new QueriesGenerated.RTQ(1, "os"));
    rtqMethods.put("6924493648261404982", new QueriesGenerated.RTQ(2, "os"));
    rtqMethods.put("8581169171144192297", new QueriesGenerated.RTQ(3, "Display"));
    rtqMethods.put("8581169171144274279", new QueriesGenerated.RTQ(4, "Display"));
    rtqMethods.put("4160282296009158683", new QueriesGenerated.RTQ(5, "inputFeature"));
    rtqMethods.put("4160282296009177262", new QueriesGenerated.RTQ(6, "inputFeature"));
    rtqMethods.put("4160282296009276058", new QueriesGenerated.RTQ(7, "outputField"));
    rtqMethods.put("4160282296009396078", new QueriesGenerated.RTQ(8, "i"));
    rtqMethods.put("4160282296009417458", new QueriesGenerated.RTQ(9, "inputFeature"));
  }
  @NotNull
  @Override
  public ReferenceTargetQuery getReferenceTargetQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(rtqMethods.containsKey(id))) {
      return super.getReferenceTargetQuery(queryKey);
    }
    return rtqMethods.get(id);
  }
  private static class RTQ extends ReferenceTargetQuery.Base {
    private final int methodKey;
    /*package*/ RTQ(int methodKey, String templateValue) {
      super(templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull ReferenceMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.referenceMacro_GetReferent_4160282296009532596(ctx);
        case 1:
          return QueriesGenerated.referenceMacro_GetReferent_6924493648261366371(ctx);
        case 2:
          return QueriesGenerated.referenceMacro_GetReferent_6924493648261404983(ctx);
        case 3:
          return QueriesGenerated.referenceMacro_GetReferent_8581169171144192298(ctx);
        case 4:
          return QueriesGenerated.referenceMacro_GetReferent_8581169171144274280(ctx);
        case 5:
          return QueriesGenerated.referenceMacro_GetReferent_4160282296009158684(ctx);
        case 6:
          return QueriesGenerated.referenceMacro_GetReferent_4160282296009177263(ctx);
        case 7:
          return QueriesGenerated.referenceMacro_GetReferent_4160282296009276059(ctx);
        case 8:
          return QueriesGenerated.referenceMacro_GetReferent_4160282296009396079(ctx);
        case 9:
          return QueriesGenerated.referenceMacro_GetReferent_4160282296009417459(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
}
