package Mobile_language.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Display = 0;
  public static final int DisplayType = 1;
  public static final int InputFeature = 2;
  public static final int InputFeatureReference = 3;
  public static final int Mobile = 4;
  public static final int OS = 5;
  public static final int OSType = 6;
  public static final int OutputField = 7;
  public static final int RAM = 8;
  public static final int RAMType = 9;
  public static final int mobileFeatures = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc5bf149de8404863L, 0x943d431a54c8f817L);
    builder.put(0x77166fe56b8cebf6L, Display);
    builder.put(0x77166fe56b8cf336L, DisplayType);
    builder.put(0x39bc4ab4c2f1c862L, InputFeature);
    builder.put(0x39bc4ab4c2f215d2L, InputFeatureReference);
    builder.put(0x39bc4ab4c2f15060L, Mobile);
    builder.put(0x6018be491a06ec5fL, OS);
    builder.put(0x6018be491a138f3aL, OSType);
    builder.put(0x39bc4ab4c2f1c8d3L, OutputField);
    builder.put(0x6018be491a0cf4c6L, RAM);
    builder.put(0x77166fe56b99906fL, RAMType);
    builder.put(0x6018be491a09dc40L, mobileFeatures);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
