package Mobile_language.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0a = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt_a0a)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Display_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new DisplayType_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new InputFeature_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new InputFeatureReference_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Mobile_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new OS_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new OSType_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new OutputField_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new RAM_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0d = concept;
    switch (index_xbvbvu_a0d.index(cncpt_a0d)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new InputFeatureReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x77166fe56b8cebf6L), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x77166fe56b8cf336L), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f1c862L), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f215d2L), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f15060L), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x6018be491a06ec5fL), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x6018be491a138f3aL), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f1c8d3L), MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x6018be491a0cf4c6L)).seal();
  private static final ConceptSwitchIndex index_xbvbvu_a0d = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f215d2L)).seal();
}
