package Mobile_language.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;

public class InputFeatureReference_SubstituteMenu extends SubstituteMenuBase {
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new InputFeatureReference_SubstituteMenu.SMP_ReferenceScope_ovebto_a(), MetaAdapterFactory.getConcept(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f215d2L, "Mobile_language.structure.InputFeatureReference")));
    return result;
  }

  @NotNull
  @Override
  public List<SubstituteMenuItem> createMenuItems(@NotNull SubstituteMenuContext context) {
    context.getEditorMenuTrace().pushTraceInfo();
    context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("default substitute menu for InputFeatureReference. Generated from implicit smart reference attribute.", new SNodePointer("r:dad244af-33cd-42a3-a6ad-306df5e2797f(Mobile_language.structure)", "4160282296008709586")));
    try {
      return super.createMenuItems(context);
    } finally {
      context.getEditorMenuTrace().popTraceInfo();
    }
  }


  public static class SMP_ReferenceScope_ovebto_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_ovebto_a() {
      super(MetaAdapterFactory.getConcept(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f215d2L, "Mobile_language.structure.InputFeatureReference"), MetaAdapterFactory.getReferenceLink(0xc5bf149de8404863L, 0x943d431a54c8f817L, 0x39bc4ab4c2f215d2L, 0x39bc4ab4c2f215eeL, "Feature"));
    }
    @NotNull
    @Override
    public List<SubstituteMenuItem> createItems(SubstituteMenuContext context) {
      context.getEditorMenuTrace().pushTraceInfo();
      context.getEditorMenuTrace().setDescriptor(new EditorMenuDescriptorBase("reference scope substitute menu part", null));
      try {
        return super.createItems(context);
      } finally {
        context.getEditorMenuTrace().popTraceInfo();
      }
    }

  }
}
